# Generated by Django 3.1.3 on 2021-12-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='links',
            new_name='likes',
        ),
    ]
