"""empty message

Revision ID: f42e08765b5b
Revises: e5b43f7688fe
Create Date: 2021-12-09 15:59:14.899014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f42e08765b5b'
down_revision = 'e5b43f7688fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_product_unique', 'product_user', ['user_id', 'product_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_product_unique', 'product_user', type_='unique')
    # ### end Alembic commands ###
